name: Terraform Security Scan
on:
  pull_request:
    branches:
      - main
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    permissions:
        contents: write
        id-token: write
        pull-requests: write

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
            soft_fail: true
            format: 'json'
            out: 'tfsec_output.json'